spring:
  application:
    name: fuck-gateway
zuul:
  #ribbon:
    #eager-load:
      #enabled: true     #zuul饥饿加载
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  routes:
    demo:
      path: /demo/**
      serviceId: demo
      sensitiveHeaders: Cookie,Set-Cookie
    auth:
      path: /login/**
      serviceId: auth-server
      sensitiveHeaders: Cookie,Set-Cookie


security:
  oauth2:
    client:
      accessTokenUri: /oauth/token
      clientId: fuck
      clientSecret: fuck
    resource:
      userInfoUri: /user
      token-info-uri: /oauth/check_token
  filter-order: 1

#自定义放行url pattern
fuck:
  permitall:
    patterns:
      - /login/**
      - /web/**
